### ISSUE TITLE
MPC-BE?

### ISSUE THREAD

**Issue by nisehime** [PCigales/DLNAmpcRenderer#2]
Is it possible to use it with mpc-be?

**Comment by nisehime** [comment]
I already tried it and the problem is that mpc-be cannot be run with /slave command. I don't know what it does, so I thought maybe you can do it without this command, or there's some alternative

**Comment by PCigales** [comment]
The /slave option is essential to the communication between the script and the app, as it allows to provide the handle of the window to which the notifications must be sent (it is explained in the link mentioned above).
I tried with mpc-be, and the script manages to communicate with the app, but the commands sent are ignored, I don't know why. I have to dig into it.
If the renderer cannot be discovered, it is probably due to the firewall. python needs incoming TCP connections from local network on local port RENDERER_TCP_PORT (as in command line), incoming UDP connections from local network on local port 1900.

**Comment by nisehime** [comment]
` If the renderer cannot be discovered, it is probably due to the firewall. python needs incoming TCP connections from local network on local port RENDERER_TCP_PORT (as in command line), incoming UDP connections from local network on local port 1900.`

I tried opening link http://192.168.1.55:9100/D_S on my phone browser and it opened. I also tried to disable firewall, but it didn't help. My PC can be discovered with Windows Media Streaming. Looks like it's not about firewall.

**Comment by PCigales** [comment]
Please, try to first launch BubbleUPnP on your phone, and then, run the script.
The discovery protocol relies on UDP on port 9100, so you may be able to fetch the xml desc file through TCP on port 9100 but the discovery datagrams not be able to reach the socket used by the script and listening on multicast port 9100.

**Comment by nisehime** [comment]
Nothing

**Comment by nisehime** [comment]
I think the script should send some ssdp packets just after start, right? It looks like it still listens on localhost despite the --bind command

**Comment by PCigales** [comment]
Yes, it does. It sends the advertisement message "alive" to 239.255.255.250:1900.
The socket for receiving search messages listens in some way on 239.255.255.250, it is a multicast address.

**Comment by nisehime** [comment]
> Did you check if the renderer can be detected by Windows Media Player running on the same host ?

I never launched WMP tbh. However, when I open network folder in explorer I get these messages in log.
```
12/05/2022 22:22:22 : Réception d'un message de recherche de renderer de 127.0.0.1:50172
12/05/2022 22:22:22 : Envoi de la réponse au message de recherche de renderer de 127.0.0.1:50172
```

The reason I thought about that is that I don't see ssdp packets on my ethernet interface in wireshark after running the script, but I see them on loopback interface with the source IP 127.0.0.1.  If I don't pass --bind command to script, IP in log will also be 127.0.0.1 for some reason. So I thought maybe that could be related.

**Comment by nisehime** [comment]
Just as I thought, the server now can be discovered in BubbleUPnP when I changed this line 

https://github.com/PCigales/DLNAmpcRenderer/blob/main/DLNAmpcRenderer.py#L2576

I wrote my IP into this quotes like that

`    with DLNASearchServer(('192.168.1.55', 1900), DLNASearchBoundHandler, verbosity=self.verbosity) as self.DLNASearchManager:`

But I think the annouce `send_advertisement` still doesn't reach my network so my TV doesn't see it.

Could you please fix it, so it would use IP passed in --bind command, and correct other methods if needed?

**Comment by nisehime** [comment]
Yeah, what I did didn't help, it was just a coincidence, but it still proved me right. I have 3 network interfaces (Eternet, Virtualbox and loopback) and somehow your program randomly decides which to use, and this choice is kept until reboot. Now it uses Virtualbox source IP. No idea why and how, anyway as I said --bind option doesn't apply to SSDP packets, which causes the problem.

**Comment by PCigales** [comment]
The script does not make any decision related to which interface will be used: the os does. That's why the choice remains the same until next reboot.
The address 239.255.255.250 is not a physical one, it is a multicast ip. Your router will forward the datagrams sent to this address to all the hosts that joined the multicast group. You can have a look at https://tldp.org/HOWTO/Multicast-HOWTO-6.html and https://stackoverflow.com/questions/46066244/what-is-the-purpose-and-result-of-using-inaddr-any for further explanations in english, that is not my native language.
When binding the socket to '' or '0.0.0.0', it listens on all interfaces. Then, you have the "self.socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, struct.pack('4sL', socket.inet_aton('239.255.255.250'), socket.INADDR_ANY))" instruction, which requests the os to choose the default interface and join the socket to the multicast group. The kernel usually makes the right choice, but in your case, it seems to be random.
As you noticed, the "--bind" option only apply to the TCP server, but it is intended like this, because of this mechanism. If the ip address of the computer on the ethernet and virtualbox interfaces is not the same, what might work is to also replace "socket.INADDR_ANY" with the ethernet ip.

You can try to open a python session and then enter:
`import socket`
`import struct`
`s=socket.socket(type=socket.SOCK_DGRAM)`
`s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)`
`s.bind(('192.168.1.55',1900))`
`s.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP,struct.pack('4s4s', socket.inet_aton('239.255.255.250'), socket.inet_aton('192.168.1.55')))`
`s.recv(1000)`
replacing 192.168.1.55 by the current ip address if it has changed,
and then run your DLNA controler, and you should see something such as b'M-SEARCH * HTTP/1.1\r\nSt: urn:schemas-upnp-org:service:AVTransport:1\r\nHost: 239.255.255.250:1900\r\nMx: 3\r\nMan: "ssdp:discover"\r\n\r\n'

It is the same for dlna advertisements. The os is supposed to choose the right interface. You can try to bind the socket to the ethernet ip just after the "sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)" instruction, with sock.bind(('192.168.1.55', 0)).

As for your TV, I wonder if it really can act as a dlna controler; otherwise, it will not send search messages for dlna renderers nor register dlna renderers sending alive advertisements.

**Comment by nisehime** [comment]
I don't know how to write it properly. I'm not a programmer. If I just write a string it doesn't work.

```
Exception in thread Thread-7:
Traceback (most recent call last):
18/05/2022 16:30:16 : Envoi du message de publicité: alive
  File "C:\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Madobe\Desktop\DLNAmpcRenderer-1.2.3\DLNAmpcRenderer.py", line 2576, in _start_search_manager
    with DLNASearchServer(('', 1900), DLNASearchBoundHandler, verbosity=self.verbosity) as self.DLNASearchManager:
  File "C:\Users\Madobe\Desktop\DLNAmpcRenderer-1.2.3\DLNAmpcRenderer.py", line 766, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python39\lib\socketserver.py", line 452, in __init__
    self.server_bind()
  File "C:\Users\Madobe\Desktop\DLNAmpcRenderer-1.2.3\DLNAmpcRenderer.py", line 770, in server_bind
    self.socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, struct.pack('4sL', socket.inet_aton('239.255.255.250'), '192.168.1.55'))
struct.error: required argument is not an integer
```

**Comment by PCigales** [comment]
I thought it was clear in my post of yesterday, where I wrote the whole sequence to test, but sorry if it is not the case, as my English is not very good.
I am going to bring the two changes, in the advertisement code and in the search message handling code, so that you can download and run the updated script.
If you face the same kind of issue with other applications, you can also lead the os to choose the ethernet interface either by lowering its metric or increasing the metric of the virtualbox. You can open a cmd window and use the route command (route print -4) to display the routing table.

**Comment by nisehime** [comment]
Sorry, I didn't pay attention, I thought it would be the same as what I tried to do. Yes, your code worked, I received this message.

> You can try to bind the socket to the ethernet ip just after the "sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)" instruction, with sock.bind(('192.168.1.55', 0)).

This is also working I guess. The only problem I can't be 100% sure since the script is binded to Ethernet interface normally right now, I don't even need --bind option.

**Comment by PCigales** [comment]
Done, new release https://github.com/PCigales/DLNAmpcRenderer/releases/tag/v1.2.4

**Comment by nisehime** [comment]
Thanks. I will report if theres any issues
